### ISSUE TITLE
Cannot get it work

### ISSUE THREAD

**Issue by JTrotta** [akkadotnet/akkadotnet-templates#80]
**Version Information**
Version of Akka.NET? LAST 
Which Akka.NET Modules? WebApiTemplate.App not modified

**Describe the bug**
Cluster not formed. I reduced the param "RequiredContactPointsNr" to 0 and to 1, but cluster never formed.

**To Reproduce**
Run the WebApiTemplate.App

**Expected behavior**
Cluster formed even with just one node

**Actual behavior**
Cluster not formed
`[INFO][05/10/2023 04:02:25.535Z][Thread 0001][remoting (akka://AkkaWebApi)] Starting remoting
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:25.535Z][Thread 0001][remoting (akka://AkkaWebApi)] Starting remoting
[INFO][05/10/2023 04:02:25.955Z][Thread 0001][remoting (akka://AkkaWebApi)] Remoting started; listening on addresses : [akka.tcp://AkkaWebApi@sviluppo1:8081]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:25.955Z][Thread 0001][remoting (akka://AkkaWebApi)] Remoting started; listening on addresses : [akka.tcp://AkkaWebApi@sviluppo1:8081]
[INFO][05/10/2023 04:02:25.956Z][Thread 0001][remoting (akka://AkkaWebApi)] Remoting now listens on addresses: [akka.tcp://AkkaWebApi@sviluppo1:8081]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:25.956Z][Thread 0001][remoting (akka://AkkaWebApi)] Remoting now listens on addresses: [akka.tcp://AkkaWebApi@sviluppo1:8081]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:25.979Z][Thread 0001][Cluster (akka://AkkaWebApi)] Cluster Node [akka.tcp://AkkaWebApi@sviluppo1:8081] - Starting up...
[INFO][05/10/2023 04:02:25.979Z][Thread 0001][Cluster (akka://AkkaWebApi)] Cluster Node [akka.tcp://AkkaWebApi@sviluppo1:8081] - Starting up...
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.012Z][Thread 0001][Cluster (akka://AkkaWebApi)] Cluster Node [akka.tcp://AkkaWebApi@sviluppo1:8081] - Started up successfully
[INFO][05/10/2023 04:02:26.012Z][Thread 0001][Cluster (akka://AkkaWebApi)] Cluster Node [akka.tcp://AkkaWebApi@sviluppo1:8081] - Started up successfully
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.048Z][Thread 0001][ClusterBootstrap (akka://AkkaWebApi)] ClusterBootstrap loaded through 'akka.extensions' auto starting bootstrap.
[INFO][05/10/2023 04:02:26.048Z][Thread 0001][ClusterBootstrap (akka://AkkaWebApi)] ClusterBootstrap loaded through 'akka.extensions' auto starting bootstrap.
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.076Z][Thread 0006][Cluster (akka://AkkaWebApi)] Cluster Node [akka.tcp://AkkaWebApi@sviluppo1:8081] - No seed-nodes configured, manual cluster join required
[INFO][05/10/2023 04:02:26.076Z][Thread 0006][Cluster (akka://AkkaWebApi)] Cluster Node [akka.tcp://AkkaWebApi@sviluppo1:8081] - No seed-nodes configured, manual cluster join required
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.180Z][Thread 0008][AkkaManagement (akka://AkkaWebApi)] Binding Akka Management (HTTP) endpoint to: fe80::a782:1c37:2b36:b3c9%22:8558
[INFO][05/10/2023 04:02:26.180Z][Thread 0008][AkkaManagement (akka://AkkaWebApi)] Binding Akka Management (HTTP) endpoint to: fe80::a782:1c37:2b36:b3c9%22:8558
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.187Z][Thread 0008][AkkaManagement (akka://AkkaWebApi)] Including HTTP management routes for ClusterBootstrap
[INFO][05/10/2023 04:02:26.187Z][Thread 0008][AkkaManagement (akka://AkkaWebApi)] Including HTTP management routes for ClusterBootstrap
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.192Z][Thread 0008][ClusterBootstrap (akka://AkkaWebApi)] Using self contact point address: http://sviluppo1:8558/
[INFO][05/10/2023 04:02:26.192Z][Thread 0008][ClusterBootstrap (akka://AkkaWebApi)] Using self contact point address: http://sviluppo1:8558/
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.290Z][Thread 0017][akka.tcp://AkkaWebApi@sviluppo1:8081/system/sharding/counter] counter: Idle entities will be passivated after [00:02:00]
[INFO][05/10/2023 04:02:26.290Z][Thread 0017][akka.tcp://AkkaWebApi@sviluppo1:8081/system/sharding/counter] counter: Idle entities will be passivated after [00:02:00]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.348Z][Thread 0008][HttpExt (akka://AkkaWebApi)] HTTP Extension started
[INFO][05/10/2023 04:02:26.348Z][Thread 0008][HttpExt (akka://AkkaWebApi)] HTTP Extension started
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.353Z][Thread 0008][AkkaManagement (akka://AkkaWebApi)] Bound Akka Management (HTTP) endpoint to: fe80::a782:1c37:2b36:b3c9%22:8558
[INFO][05/10/2023 04:02:26.353Z][Thread 0008][AkkaManagement (akka://AkkaWebApi)] Bound Akka Management (HTTP) endpoint to: fe80::a782:1c37:2b36:b3c9%22:8558
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.367Z][Thread 0044][akka://AkkaWebApi/system/healthcheck-readiness-cluster] Message [CurrentClusterState] from [akka://AkkaWebApi/system/cluster/core/publisher#941467490] to [akka://AkkaWebApi/system/healthcheck-readiness-cluster#905071351] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'. Message content: Akka.Cluster.ClusterEvent+CurrentClusterState
[INFO][05/10/2023 04:02:26.367Z][Thread 0044][akka://AkkaWebApi/system/healthcheck-readiness-cluster] Message [CurrentClusterState] from [akka://AkkaWebApi/system/cluster/core/publisher#941467490] to [akka://AkkaWebApi/system/healthcheck-readiness-cluster#905071351] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'. Message content: Akka.Cluster.ClusterEvent+CurrentClusterState
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.406Z][Thread 0008][ClusterBootstrap (akka://AkkaWebApi)] Initiating bootstrap procedure using akka.discovery method...
[INFO][05/10/2023 04:02:26.406Z][Thread 0008][ClusterBootstrap (akka://AkkaWebApi)] Initiating bootstrap procedure using akka.discovery method...
warn: Akka.Actor.ActorSystem[0]
      [WARNING][05/10/2023 04:02:26.448Z][Thread 0008][Discovery (akka://AkkaWebApi)] No default service discovery implementation configured in `akka.discovery.method`.
Make sure to configure this setting to your preferred implementation such as 'config'
in your application.conf (from the akka-discovery module). Falling back to default config
based discovery method
[WARNING][05/10/2023 04:02:26.448Z][Thread 0008][Discovery (akka://AkkaWebApi)] No default service discovery implementation configured in `akka.discovery.method`.
Make sure to configure this setting to your preferred implementation such as 'config'
in your application.conf (from the akka-discovery module). Falling back to default config
based discovery method
[INFO][05/10/2023 04:02:26.452Z][Thread 0008][Discovery (akka://AkkaWebApi)] Starting Discovery service using [config] method, class: [Akka.Discovery.Config.ConfigServiceDiscovery, Akka.Discovery]
[WARNING][05/10/2023 04:02:26.466Z][Thread 0008][ConfigServiceDiscovery (akka://AkkaWebApi)] You are trying to use config based discovery service and the settings path [akka.discovery.config.services]
described `akka.discovery.config.services-path` is empty. Make sure to fill this setting
with pre-defined node addresses to make sure that a cluster can be formed.
[INFO][05/10/2023 04:02:26.467Z][Thread 0008][ClusterBootstrap (akka://AkkaWebApi)] Bootstrap using default `akka.discovery` method: ConfigServiceDiscovery
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.452Z][Thread 0008][Discovery (akka://AkkaWebApi)] Starting Discovery service using [config] method, class: [Akka.Discovery.Config.ConfigServiceDiscovery, Akka.Discovery]
warn: Akka.Actor.ActorSystem[0]
      [WARNING][05/10/2023 04:02:26.466Z][Thread 0008][ConfigServiceDiscovery (akka://AkkaWebApi)] You are trying to use config based discovery service and the settings path [akka.discovery.config.services]
described `akka.discovery.config.services-path` is empty. Make sure to fill this setting
with pre-defined node addresses to make sure that a cluster can be formed.
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.467Z][Thread 0008][ClusterBootstrap (akka://AkkaWebApi)] Bootstrap using default `akka.discovery` method: ConfigServiceDiscovery
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.488Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Locating service members. Using discovery [ConfigServiceDiscovery], join decider [LowestAddressJoinDecider], scheme [http]
[INFO][05/10/2023 04:02:26.488Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Locating service members. Using discovery [ConfigServiceDiscovery], join decider [LowestAddressJoinDecider], scheme [http]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.493Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
[INFO][05/10/2023 04:02:26.493Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:26.504Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
[INFO][05/10/2023 04:02:26.504Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
warn: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[8]
      The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\C#COMP\AKKA\akkadotnet-templates\src\WebApiTemplate\src\WebApiTemplate.App
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:27.582Z][Thread 0009][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:27.582Z][Thread 0009][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
[INFO][05/10/2023 04:02:27.582Z][Thread 0009][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
[INFO][05/10/2023 04:02:27.582Z][Thread 0009][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:28.804Z][Thread 0044][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
[INFO][05/10/2023 04:02:28.804Z][Thread 0044][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:28.804Z][Thread 0044][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
[INFO][05/10/2023 04:02:28.804Z][Thread 0044][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:29.834Z][Thread 0008][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
[INFO][05/10/2023 04:02:29.834Z][Thread 0008][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:29.834Z][Thread 0008][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
[INFO][05/10/2023 04:02:29.834Z][Thread 0008][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:30.908Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:30.908Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
[INFO][05/10/2023 04:02:30.908Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Looking up [Lookup(akka-management, management, tcp)]
[INFO][05/10/2023 04:02:30.908Z][Thread 0043][akka.tcp://AkkaWebApi@sviluppo1:8081/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-management, management, tcp)]: [], filtered to []
info: Akka.Actor.ActorSystem[0]
      [INFO][05/10/2023 04:02:31.565Z][Thread 0045][SelfAwareJoinDecider (akka://AkkaWebApi)] Exceeded stable margins without locating seed-nodes, however this node sviluppo1:8558 is NOT the lowest address out of the discovered endpoints in this deployment, thus NOT joining self. Expecting node [] (out of []) to perform the self-join and initiate the cluster.
[INFO][05/10/2023 04:02:31.565Z][Thread 0045][SelfAwareJoinDecider (akka://AkkaWebApi)] Exceeded stable margins without locating seed-nodes, however this node sviluppo1:8558 is NOT the lowest address out of the discovered endpoints in this deployment, thus NOT joining self. Expecting node [] (out of []) to perform the self-join and initiate the cluster.`

**Environment**
Windows .NET 7.0

**Additional context**

**Comment by Aaronontheweb** [comment]
cc @arkatufus

**Comment by Arkatufus** [comment]
Reproduction step:
* Create a new project using `dotnet new akkawebapi`
* Change "AkkaManagementOptions" "Enabled" in `appsettings.json` to true
* Run the project in the default run configuration

Cause:
The `DiscoveryMethod.Config` section of the switch statement is empty, configuration based cluster bootstraping was not configured correctly in code.
https://github.com/akkadotnet/akkadotnet-templates/blob/7fbf98e0aff8743d8358ad5902e3e737b7328741/src/WebApiTemplate/src/WebApiTemplate.App/Configuration/AkkaConfiguration.cs#L101-L102

**Comment by Aaronontheweb** [comment]
> Reproduction step:
> 
> * Create a new project using `dotnet new akkawebapi`
> * Change "AkkaManagementOptions" "Enabled" in `appsettings.json` to true
> * Run the project in the default run configuration
> 
> Cause: The `DiscoveryMethod.Config` section of the switch statement is empty, configuration based cluster bootstraping was not configured correctly in code.
> 
> https://github.com/akkadotnet/akkadotnet-templates/blob/7fbf98e0aff8743d8358ad5902e3e737b7328741/src/WebApiTemplate/src/WebApiTemplate.App/Configuration/AkkaConfiguration.cs#L101-L102

Do we need to add some default config someplace? Or a warning?

**Comment by Arkatufus** [comment]
We should at least add a configuration based discovery configuration, I think

**Comment by Aaronontheweb** [comment]
> We should at least add a configuration based discovery configuration, I think

Agree, can you send in a PR for this?
